name: Black

on: [push]

jobs:
  formatting-with-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
              
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q black "black[jupyter]"
        
    - name: Formatting the code with Black
      run: |
        black --ipynb --check --line-length 79 --exclude utils.py .
