name: !!str Fix

on: !!str workflow_dispatch

jobs: !!map
  format: !!map
    runs-on: !!str ubuntu-latest
    permissions: !!map
      contents: !!str write
    steps: !!seq
    - uses: !!str actions/checkout@v3
      with: !!map
        persist-credentials: !!bool false
        fetch-depth: !!int 0
    
    - name: !!str Set up Python
      uses: !!str actions/setup-python@v3
          
    - name: !!str Install dependencies
      run: !!str |
        python -m pip install --upgrade pip
        pip install ruff nbqa
                
    - name: !!str Fixing the code
      run: !!str nbqa ruff . --fix
    
    - name: !!str Commit files
      run: !!str |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Formatting notebook"
        
    - name: !!str Push changes
      uses: !!str ad-m/github-push-action@master
      with: !!map
        github_token: !!str ${{ secrets.GITHUB_TOKEN }}
        branch: !!str ${{ github.ref }}
