name: !!str Ruff

on: !!map
  push : !!map
    branches: !!str main
  workflow_run: !!map
    workflows: !!seq ["Black", "Fix"]
    types: !!str completed

jobs: !!map
  lint: !!map
    runs-on: !!str ubuntu-latest
    steps: !!seq
    - uses: !!str actions/checkout@v3
    
    - name: !!str Set up Python
      uses: !!str actions/setup-python@v3
          
    - name: !!str Install dependencies
      run: !!str |
        python -m pip install --upgrade pip
        pip install ruff nbqa
                
    - name: !!str Analysing the code
      run: !!str nbqa ruff .
