name: !!str Tree

on: !!str workflow_dispatch

jobs: !!map
  generate: !!map
    runs-on: !!str ubuntu-latest
    permissions: !!map
      contents: !!str write

    steps: !!seq
    - name: !!str 'Checkout Repository'
      uses: !!str actions/checkout@v3
      with: !!map
        persist-credentials: !!bool false
        fetch-depth: !!int 0
            
    - name: !!str Running script
      run: !!str |
        tree --noreport -I 'README.md|LICENSE|tree.txt' > tree.txt
        sed -i "15,100d" README.md
        echo '```' >> tree.txt 
        cat tree.txt >> README.md

    - name: !!str Showing result
      run: !!str cat README.md
            
    - name: !!str Commit files
      run: !!str |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"        
        git commit -am "Update tree"
        
    - name: !!str Push changes
      uses: !!str ad-m/github-push-action@master
      with:
        github_token: !!str ${{ secrets.GITHUB_TOKEN }}
        branch: !!str ${{ github.ref }}
